// import VueResource from 'vue-resource'

// Vue.use(VueResource);

var vue_app_display = new Vue({
	el:"#vue_app_display",
	data:{
			pm_monitoring_time_bit:false,
			pm_limit_bit:false,
			pm_mdi_bit:false,
			pm_load_profile_bit:false,
			pm_clock_calibration_bit:false,
			pm_decimal_point_bit:false,
			pm_energy_bit:false,
			pm_season_setting_bit:false,
			pm_tariff_setting_bit:false,
			pm_season_a_bit:false,
			pm_season_b_bit:false,
			pm_season_c_bit:false,
			pm_season_d_bit:false,
			pm_calender_setting_bit:false,
			pm_display_windows_bit:false,
			pm_power_off_display_bit:false,
			pm_password_bit:false,
			pm_cautions_and_errors_bit:false,
			monthly_billing_data_bit:false,
			cummulative_billing_bit:false,
			instantaneous_bit:true,
			load_profile_bit:false,
			event_bit:false,
			pm_default_parameters_bit:false,

			mt:{
				power_outage:{
					value_in_secs:5,
				},
				ct_bypass:{
					value_in_secs:5,
				},
				phase_fail:{
					value_in_secs:5,
				},
				pt_bypass:{
					value_in_secs:5,
				},
				over_voltage:{
					value_in_secs:5,
				},
				imbalance_voltage:{
					value_in_secs:5,
				},
				under_voltage:{
					value_in_secs:5,
				},
				mdi_exceed:{
					value_in_secs:5,
				},
				demand_overload:{
					value_in_secs:5,
				},
				phase_sequence_change:{
					value_in_secs:5,
				},
				reverse_energy_flow:{
					value_in_secs:5,
				},
				tamper_energy:{
					value_in_secs:5,
				},
				reverse_polarity:{
					value_in_secs:5,
				},
				over_current:{
					value_in_secs:5,
				},
			},
			lm:{
				over_voltage:{
					value_in_unit:240,
				},
				reverse_energy:{
					value_in_unit:0.001,
				},
				under_voltage:{
					value_in_unit:0.001,
				},
				ct_current:{
					value_in_unit:0.001,
				},
				demand_overload:{
					value_in_unit:0.001,
				},
				pt_voltage:{
					value_in_unit:0.001,
				},
				imbalance_voltage:{
					value_in_unit:0.001,
				},
				mdi_exceed:{
					value_in_unit:0.001,
				},
				over_current:{
					value_in_unit:0.001,
				},
				tamper_energy:{
					value_in_unit:0.001,
				},
			},
			inst:{
				voltage_phase_a:{
					value:0.0,
					unit:"",
				},
				current_phase_a:{
					value:0.0,
					unit:"",
				},
				active_power_phase_a:{
					value:0.0,
					unit:"",
				},
				reactive_power_phase_a:{
					value:0.0,
					unit:"",
				},
				apparent_power_phase_a:{
					value:0.0,
					unit:"",
				},
				power_factor_phase_a:{
					value:0.0,
					unit:"",
				},
				power_quadrant_phase_a:{
					value:0.0,
					unit:"",
				},
				voltage_phase_b:{
					value:0.0,
					unit:"",
				},
				current_phase_b:{
					value:0.0,
					unit:"",
				},
				active_power_phase_b:{
					value:0.0,
					unit:"",
				},
				reactive_power_phase_b:{
					value:0.0,
					unit:"",
				},
				apparent_power_phase_b:{
					value:0.0,
					unit:"",
				},
				power_factor_phase_b:{
					value:0.0,
					unit:"",
				},
				power_quadrant_phase_b:{
					value:0.0,
					unit:"",
				},
				voltage_phase_c:{
					value:0.0,
					unit:"",
				},
				current_phase_c:{
					value:0.0,
					unit:"",
				},
				active_power_phase_c:{
					value:0.0,
					unit:"",
				},
				reactive_power_phase_c:{
					value:0.0,
					unit:"",
				},
				apparent_power_phase_c:{
					value:0.0,
					unit:"",
				},
				power_factor_phase_c:{
					value:0.0,
					unit:"",
				},
				power_quadrant_phase_c:{
					value:0.0,
					unit:"",
				},
				current_all_phases:{
					value:0.0,
					unit:"",
				},
				active_power_all_phases:{
					value:0.0,
					unit:"",
				},
				reactive_power_all_phases:{
					value:0.0,
					unit:"",
				},
				apparent_power_all_phases:{
					value:0.0,
					unit:"",
				},
				power_factor_all_phases:{
					value:0.0,
					unit:"",
				},
				power_quadrant_all_phases:{
					value:0.0,
					unit:"",
				},
				active_current_month_mdi_t_1:{
					value:0.0,
					unit:"",
				},
				reactive_current_month_mdi_t_1:{
					value:0.0,
					unit:"",
				},
				active_current_month_mdi_t_2:{
					value:0.0,
					unit:"",
				},
				reactive_current_month_mdi_t_2:{
					value:0.0,
					unit:"",
				},
				active_current_month_mdi_t_3:{
					value:0.0,
					unit:"",
				},
				reactive_current_month_mdi_t_3:{
					value:0.0,
					unit:"",
				},
				active_current_month_mdi_t_4:{
					value:0.0,
					unit:"",
				},
				reactive_current_month_mdi_t_4:{
					value:0.0,
					unit:"",
				},
				active_current_month_mdi_t_L:{
					value:0.0,
					unit:"",
				},
				reactive_current_month_mdi_t_L:{
					value:0.0,
					unit:"",
				},
				meter_date:{
					value:0.0,
					unit:"",
				},
				meter_time:{
					value:0.0,
					unit:"",
				},
				mdi_reset_count:{
					value:0.0,
					unit:"",
				},
				season:{
					value:0.0,
					unit:"",
				},
				tariff:{
					value:0.0,
					unit:"",
				},
				frequency:{
					value:0.0,
					unit:"",
				},
				time_interval_left:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kw:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_import_kw:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_export_kw:{
					value:0.0,
					unit:"",
				},
				tamper_power:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_import_kvar:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_export_kvar:{
					value:0.0,
					unit:"",
				},
				counter:{
					value:0.0,
					unit:"",
				},
				slide_count:{
					value:0.0,
					unit:"",
				},
				slide_counter:{
					value:0.0,
					unit:"",
				},
				time_period:{
					value:0.0,
					unit:"",
				},
				time_span_index:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_slide_1:{
					value:0.0,
					unit:"",
				},

				active_mdi_kw_import_slide_1:{
					value:0.0,
					unit:"",
				},

				active_mdi_kw_export_slide_1:{
					value:0.0,
					unit:"",
				},

				reactive_mdi_kvar_slide_1:{
					value:0.0,
					unit:"",
				},

				reactive_mdi_kvar_import_slide_1:{
					value:0.0,
					unit:"",
				},

				reactive_mdi_kvar_export_slide_1:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_slide_2:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_import_slide_2:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_export_slide_2:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_slide_2:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_import_slide_2:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_export_slide_2:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_slide_3:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_import_slide_3:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_export_slide_3:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_slide_3:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_import_slide_3:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_export_slide_3:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_slide_4:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_import_slide_4:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_export_slide_4:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_slide_4:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_import_slide_4:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_export_slide_4:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_slide_5:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_import_slide_5:{
					value:0.0,
					unit:"",
				},
				active_mdi_kw_export_slide_5:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_slide_5:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_import_slide_5:{
					value:0.0,
					unit:"",
				},
				reactive_mdi_kvar_export_slide_5:{
					value:0.0,
					unit:"",
				},
				meter_date:{
					value:0.0,
					unit:"",
				},
				meter_time:{
					value:0.0,
					unit:"",
				},
				mdi_reset_count:{
					value:0.0,
					unit:"",
				},
				running_season:{
					value:0.0,
					unit:"",
				},
				running_tariff:{
					value:0.0,
					unit:"",
				},
				frequency_hz:{
					value:0.0,
					unit:"",
				},
				time_left_interval:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kw:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kw_import:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kw_export:{
					value:0.0,
					unit:"",
				},
				tamper_power:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kvar_import:{
					value:0.0,
					unit:"",
				},
				last_interval_mdi_kvar_export:{
					value:0.0,
					unit:"",
				},
				counter:{
					value:0.0,
					unit:"",
				},
				slide_count:{
					value:0.0,
					unit:"",
				},
				slide_counter:{
					value:0.0,
					unit:"",
				},
				time_period:{
					value:0.0,
					unit:"",
				},
				time_span_index:{
					value:0.0,
					unit:"",
				},
			},
			cum:{
				kwh_absolute:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_l:{
					value:0.0,
					unit:"",
				},
				average_pf:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_1:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_2:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_3:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_4:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvah_total:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_l:{
					value:0.0,
					unit:"",
				},
				tamper_energy:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_1:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_2:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_3:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_4:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_abs:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kwh_import:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_import:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_import:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kwh_export:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_export:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_export:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q1:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q2:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q3:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q4:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_l:{
					value:0.0,
					unit:"",
				},
			},
			mon:{
				kwh_absolute:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_absolute_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_absolute_tariff_l:{
					value:0.0,
					unit:"",
				},
				average_pf:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_1:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_2:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_3:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_4:{
					value:0.0,
					unit:"",
				},
				average_pf_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvah_total:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvah_total_tariff_l:{
					value:0.0,
					unit:"",
				},
				tamper_energy:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_1:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_2:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_3:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_4:{
					value:0.0,
					unit:"",
				},
				tamper_energy_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_abs:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_abs_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kwh_import:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_import:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_import:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_import_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kwh_export:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				kwh_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_export:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kw_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				pf_export:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				pf_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				cumulative_mdi_kvar_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kw_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_tariff_l:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_1:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_2:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_3:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_4:{
					value:0.0,
					unit:"",
				},
				current_month_mdi_kvar_export_date_time_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q1:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q1_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q2:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q2_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q3:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q3_tariff_l:{
					value:0.0,
					unit:"",
				},
				kvarh_q4:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_1:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_2:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_3:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_4:{
					value:0.0,
					unit:"",
				},
				kvarh_q4_tariff_l:{
					value:0.0,
					unit:"",
				},
			},
	},
	methods:{
		init_all_bits:function(){
			this.pm_default_parameters_bit=false;
			this.pm_monitoring_time_bit=false;
			this.pm_limit_bit=false;
			this.pm_mdi_bit=false;
			this.pm_load_profile_bit=false;
			this.pm_clock_calibration_bit=false;
			this.pm_decimal_point_bit=false;
			this.pm_energy_bit=false;
			this.pm_season_setting_bit=false;
			this.pm_tariff_setting_bit=false;
			this.pm_season_a_bit=false;
			this.pm_season_b_bit=false;
			this.pm_season_c_bit=false;
			this.pm_season_d_bit=false;
			this.pm_calender_setting_bit=false;
			this.pm_display_windows_bit=false;
			this.pm_power_off_display_bit=false;
			this.pm_password_bit=false;
			this.pm_cautions_and_errors_bit=false;
			this.monthly_billing_data_bit=false;
			this.cummulative_billing_bit=false;
			this.instantaneous_bit=false;
			this.load_profile_bit=false;
			this.event_bit=false;
		},
		error_checking:function(event){
			console.log(event);
			event.target.classList.remove('form-control-success','form-control-danger');
			event.srcElement.parentElement.parentElement.classList.remove('has-success','has-danger');
			if((parseInt(event.target.value) >= parseInt(event.srcElement.min)) && (parseInt(event.target.value) <= parseInt(event.srcElement.max)))
			{
				event.target.classList.add('form-control-success');
				event.srcElement.parentElement.parentElement.classList.add('has-success');
			}
			else
			{
				event.target.classList.add('form-control-warning');
				event.srcElement.parentElement.parentElement.classList.add('has-danger');
			}
		},
	},
})

var vue_app_data_nav = new Vue({
	el:"#vue_app_data_nav",
	data:{

	},
	methods:{
		mb_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.monthly_billing_data_bit = true;
		},
		cb_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.cummulative_billing_bit = true;
		},
		in_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.instantaneous_bit = true;
		},
		lp_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.load_profile_bit = true;
		},
		ev_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.event_bit = true;
		},
		mt_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_monitoring_time_bit = true;
		},
		lm_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_limit_bit = true;
		},
		md_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_mdi_bit = true;
		},
		lp_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_load_profile_bit = true;
		},
		cc_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_clock_calibration_bit = true;
		},
		dp_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_decimal_point_bit = true;
		},
		ep_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_energy_bit = true;
		},
		ss_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_season_setting_bit = true;
		},
		ts_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_tariff_setting_bit = true;
		},
		sa_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_season_a_bit = true;
		},
		sb_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_season_b_bit = true;
		},
		sc_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_season_c_bit = true;
		},
		sd_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_season_d_bit = true;
		},
		cs_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_calender_setting_bit = true;
		},
		dw_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_display_windows_bit = true;
		},
		po_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_power_off_display_bit = true;
		},
		ps_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_password_bit = true;
		},
		ce_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_cautions_and_errors_bit = true;
		},
		depr_on:function(){
			vue_app_display.init_all_bits();
			vue_app_display.pm_default_parameters_bit = true;
		},
	},
})

function on(s){
	switch(s){
		case 'mb':
			vue_app_data_nav.mb_on();
			break;
		case 'cb':
			vue_app_data_nav.cb_on();
			break;
		case 'in':
			vue_app_data_nav.in_on();
			break;
		case 'lps':
			vue_app_data_nav.lp_on();
			break;
		case 'ev':
			vue_app_data_nav.ev_on();
			break;
		case'mt':
			vue_app_data_nav.mt_on();
			break;
		case'lm':
			vue_app_data_nav.lm_on();
			break;
		case'md':
			vue_app_data_nav.md_on();
			break;
		case'lp':
			vue_app_data_nav.lp_on();
			break;
		case'cc':
			vue_app_data_nav.cc_on();
			break;
		case'dp':
			vue_app_data_nav.dp_on();
			break;
		case'ep':
			vue_app_data_nav.ep_on();
			break;
		case'ss':
			vue_app_data_nav.ss_on();
			break;
		case'ts':
			vue_app_data_nav.ts_on();
			break;
		case'sa':
			vue_app_data_nav.sa_on();
			break;
		case'sb':
			vue_app_data_nav.sb_on();
			break;
		case'sc':
			vue_app_data_nav.sc_on();
			break;
		case'sd':
			vue_app_data_nav.sd_on();
			break;
		case'cs':
			vue_app_data_nav.cs_on();
			break;
		case'dw':
			vue_app_data_nav.dw_on();
			break;
		case'po':
			vue_app_data_nav.po_on();
			break;
		case'ps':
			vue_app_data_nav.ps_on();
			break;
		case'ce':
			vue_app_data_nav.ce_on();
			break;
		case 'depr':
			vue_app_data_nav.depr_on();

		default: return;
	}
}
